stages:
  create_database:
    cmd: sqlite3 data/database.db < src/sql/init.sql
    deps:
    - data/account.csv
    - data/card_dev.csv
    - data/client.csv
    - data/disp.csv
    - data/district.csv
    - data/loan_dev.csv
    - data/trans_dev.csv
    - src/sql/init.sql
    - src/sql/create.sql
    outs:
    - data/database.db
  process-data:
    cmd: python3 src/process_data.py
    deps:
    - data/database.db
    - src/process_data.py
    outs:
    - data/processed_data.csv
  split-data:
    cmd: python3 src/split_data.py
    deps:
    - data/processed_data.csv
    - src/split_data.py
    outs:
    - data/X_train.csv
    - data/y_train.csv
  train-model:
    cmd: python3 src/train_model.py
    deps:
    - data/X_test.csv
    - data/X_train.csv
    - data/y_test.csv
    - data/y_train.csv
    - src/train_model.py
    outs:
    - data/model.joblib
    params:
      - train.max_depth
  test-model:
    cmd: python3 src/test_model.py
    deps:
    - data/X_test.csv
    - data/model.joblib
    - data/y_test.csv
    - src/test_model.py
    metrics:
    - metrics/results.json:
        cache: false
    plots:
    - evaluation/plots/precision_recall.json:
        cache: false
        x: recall
        y: precision
        title: Precision-Recall Curve
    - evaluation/plots/roc.json:
        cache: false
        x: fpr
        y: tpr
        title: ROC Curve
