stages:
  create-database:
    cmd: sqlite3 data/database.db ".read src/sql/init.sql" ".read src/sql/create_data_integration_views.sql" ".read src/sql/create_data_feature_engineering_views.sql"
    deps:
    - data/card_dev.csv
    - data/client.csv
    - data/disp.csv
    - data/district.csv
    - data/loan_dev.csv
    - data/trans_dev.csv
    - src/sql/init.sql
    - src/sql/create.sql
    - src/sql/create_data_integration_views.sql
    - src/sql/create_data_feature_engineering_views.sql
    outs:
    - data/database.db
  unify-data:
    cmd: python3 src/unify_data.py
    deps:
    - data/database.db
    - src/unify_data.py
    outs:
    - data/unified_data.csv
  clean-redundancy:
    cmd: python3 src/data-cleaning/redundancy.py
    deps:
    - data/unified_data.csv
    - src/data-cleaning/redundancy.py
    outs:
    - data/clean_data0.csv
  clean-missing-data:
    cmd: python3 src/data-cleaning/missing_data.py
    deps:
    - data/clean_data0.csv
    - src/data-cleaning/missing_data.py
    outs:
    - data/clean_data1.csv
  clean-outliers:
    cmd: python3 src/data-cleaning/outliers.py
    deps:
    - data/clean_data1.csv
    - src/data-cleaning/outliers.py
    outs:
    - data/clean_data.csv
  transform-data:
    cmd: python3 src/data_transformation.py
    deps:
    - data/clean_data.csv
    - src/data_transformation.py
    outs:
    - data/prepared_data.csv 
    - data/scaler.joblib
  clustering:
    cmd: python3 src/cluster_data.py
    deps:
    - data/prepared_data.csv
    - data/scaler.joblib
    - src/cluster_data.py
  split-data:
    cmd: python3 src/split_data.py
    deps: 
    - data/prepared_data.csv
    - src/split_data.py
    outs:
    - data/X_test_all_features.csv
    - data/X_train_not_sampled.csv
    - data/y_test.csv
    - data/y_train_not_sampled.csv
  sample-data:
    cmd: python3 src/sample_data.py
    deps:
    - data/X_train_not_sampled.csv
    - data/y_train_not_sampled.csv
    - src/sample_data.py
    outs:
    - data/X_train_all_features.csv
    - data/y_train.csv
  select-features:
    cmd: python3 src/feature_selection.py
    deps:
        - data/X_test_all_features.csv
        - data/X_train_all_features.csv
        - data/y_train.csv
        - src/feature_selection.py
    outs:
    - data/X_test.csv
    - data/X_train.csv
    - data/features.csv
    params:
    - feature_selection
    - manual_feature_selection
    - manual_feature_selection_fields
  train-model:
    cmd: python3 src/train_model.py
    deps:
    - data/X_test.csv
    - data/X_train.csv
    - data/y_test.csv
    - data/y_train.csv
    - src/train_model.py
    outs:
    - data/model.joblib
    params:
    - params
    - classifiers
    metrics:
    - metrics/model_details.json:
        cache: false
  test-model:
    cmd: python3 src/test_model.py
    deps:
    - data/X_test.csv
    - data/model.joblib
    - data/y_test.csv
    - src/test_model.py
    metrics:
    - metrics/results.json:
        cache: false
    plots:
    - evaluation/plots/precision_recall.json:
        cache: false
        x: recall
        y: precision
        title: Precision-Recall Curve

