stages:
  create-database:
    cmd: sqlite3 data/database.db ".read src/sql/init.sql" ".read src/sql/create_data_integration_views.sql" ".read src/sql/create_data_feature_engineering_views.sql"
    deps:
    - data/card_dev.csv
    - data/client.csv
    - data/disp.csv
    - data/district.csv
    - data/loan_dev.csv
    - data/trans_dev.csv
    - src/sql/init.sql
    - src/sql/create.sql
    - src/sql/create_data_integration_views.sql
    - src/sql/create_data_feature_engineering_views.sql
    outs:
    - data/database.db
  unify-data:
    cmd: python3 src/unify_data.py
    deps:
    - data/database.db
    - src/unify_data.py
    outs:
    - data/unified_data.csv
  clean-redundancy:
    cmd: python3 src/data-cleaning/redundancy.py
    deps:
    - data/unified_data.csv
    - src/data-cleaning/redundancy.py
    outs:
    - data/clean_data0.csv
  clean-missing-data:
    cmd: python3 src/data-cleaning/missing_data.py
    deps:
    - data/clean_data0.csv
    - src/data-cleaning/missing_data.py
    outs:
    - data/clean_data1.csv
  clean-outliers:
    cmd: python3 src/data-cleaning/outliers.py
    deps:
    - data/clean_data1.csv
    - src/data-cleaning/outliers.py
    outs:
    - data/clean_data.csv
  transform-data:
    cmd: python3 src/data_transformation.py
    deps:
    - data/clean_data.csv
    - src/data_transformation.py
    outs:
    - data/prepared_data.csv 
  split-data:
    cmd: python3 src/split_data.py
    deps: 
    - data/prepared_data.csv
    - src/split_data.py
    outs:
    - data/X_test_all_features.csv
    - data/X_train_not_sampled.csv
    - data/y_test.csv
    - data/y_train_not_sampled.csv
  sample-data:
    cmd: python3 src/sample_data.py
    deps:
    - data/X_train_not_sampled.csv
    - data/y_train_not_sampled.csv
    - src/sample_data.py
    outs:
    - data/X_train_all_features.csv
    - data/y_train.csv
  select-features:
    cmd: python3 src/feature_selection.py
    deps:
        - data/X_test_all_features.csv
        - data/X_train_all_features.csv
        - data/y_train.csv
        - src/feature_selection.py
    outs:
    - data/X_test.csv
    - data/X_train.csv
    params:
    - feature_selection
  train-model:
    cmd: python3 src/train_model.py
    deps:
    - data/X_test.csv
    - data/X_train.csv
    - data/y_test.csv
    - data/y_train.csv
    - src/train_model.py
    outs:
    - data/model.joblib
    params:
    - train
  test-model:
    cmd: python3 src/test_model.py
    deps:
    - data/X_test.csv
    - data/model.joblib
    - data/y_test.csv
    - src/test_model.py
    metrics:
    - metrics/results.json:
        cache: false
    plots:
    - evaluation/plots/precision_recall.json:
        cache: false
        x: recall
        y: precision
        title: Precision-Recall Curve
    - evaluation/plots/roc.json:
        cache: false
        x: fpr
        y: tpr
        title: ROC Curve
  plot-data:
    cmd: python3 src/data-analysis/account.py && python3 src/data-analysis/client.py && python3 src/data-analysis/district.py && python3 src/data-analysis/loan.py
    deps:
    - data/database.db
    - src/data-analysis/account.py
    - src/data-analysis/client.py
    - src/data-analysis/district.py
    - src/data-analysis/loan.py
    outs:
    - analysis_plots/accounts_created_per_year.png:
        cache: false
    - analysis_plots/clients_sex_distribution.png:
        cache: false
    - analysis_plots/corr_accounts_per_district_with_district_table.png:
        cache: false
    - analysis_plots/district_corr.png:
        cache: false
    - analysis_plots/district_loan_by_district.png:
        cache: false
    - analysis_plots/district_loan_by_region.png:
        cache: false
    - analysis_plots/issuance_frequency_categories_count.png:
        cache: false
    - analysis_plots/loan_amount_boxplot.png:
        cache: false
    - analysis_plots/loan_amount_distribution0.png:
        cache: false
    - analysis_plots/loan_amount_distribution1.png:
        cache: false
    - analysis_plots/loan_amount_over_time.png:
        cache: false
    - analysis_plots/number_clients_per_decade_birth.png:
        cache: false
    - analysis_plots/top10_districts_most_accounts.png:
        cache: false
