stages:
  create_database:
    cmd: sqlite3 data/database.db < src/sql/init.sql
    deps:
    - data/account.csv
    - data/card_dev.csv
    - data/client.csv
    - data/disp.csv
    - data/district.csv
    - data/loan_dev.csv
    - data/trans_dev.csv
    - src/sql/init.sql
    - src/sql/create.sql
    outs:
    - data/database.db
  process-data:
    cmd: python3 src/process_data.py
    deps:
    - data/database.db
    - src/process_data.py
    outs:
    - data/processed_data.csv
