params: {}
classifiers:
- dt
- knn
- rf
- svm
- nb
- ada
feature_selection:
  filter: kbest
  wrapper: none
  estimator: 'perceptron'
manual_feature_selection: false
manual_feature_selection_fields:
- balance
- timesIntoNegativeBalance
- numTransactionsNegBalance