params: {}
classifiers:
- rf
feature_selection:
  filter: variance
  wrapper: none
  estimator: perceptron
manual_feature_selection: false
manual_feature_selection_fields:
- balance
- timesIntoNegativeBalance
- numTransactionsNegBalance
