params: {}
classifiers:
- dt
- knn
- rf
feature_selection:
  filter: kbest
  wrapper: none
  estimator: 'perceptron'
manual_feature_selection: true
manual_feature_selection_fields:
- balance
- timesIntoNegativeBalance
- numTransactionsNegBalance