params: {}
classifiers:
- knn
feature_selection:
  filter: variance
  wrapper: forward
  estimator: perceptron
manual_feature_selection: false
manual_feature_selection_fields:
- balance
- timesIntoNegativeBalance
- numTransactionsNegBalance
