params: {}
classifiers:
- dt
feature_selection:
  filter: kbest
  wrapper: none
  estimator: 'perceptron'
manual_feature_selection: false
manual_feature_selection_fields:
- balance
- timesIntoNegativeBalance
- numTransactionsNegBalance